//! API layer — inbound trait contracts and public types.
pub mod builder;
pub(crate) mod ingress_error;
pub(crate) mod daemon;
pub(crate) mod file;
pub(crate) mod file_inbound;
pub(crate) mod grpc;
pub(crate) mod grpc_inbound;
pub(crate) mod health_check;
pub(crate) mod http;
pub(crate) mod http_inbound;
pub(crate) mod inbound_source;
pub(crate) mod metrics;
pub(crate) mod middleware;
pub(crate) mod pagination;
pub(crate) mod pipeline;
pub(crate) mod rate_limiter;
pub(crate) mod traits;
pub(crate) mod validator;
